#!/usr/bin/env node
/**
 * Sync packages/core/src/version.ts with the version in package.json.
 * Runs automatically before every core build (see "prebuild" script) so the
 * CLI banner and the exported VERSION constant can never drift again.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const coreDir = path.resolve(__dirname, '..', 'packages', 'core');

const pkg = JSON.parse(fs.readFileSync(path.join(coreDir, 'package.json'), 'utf-8'));
const versionFile = path.join(coreDir, 'src', 'version.ts');

const contents = `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
export const VERSION = '${pkg.version}';
`;

const current = fs.existsSync(versionFile) ? fs.readFileSync(versionFile, 'utf-8') : '';
if (current !== contents) {
  fs.writeFileSync(versionFile, contents);
  console.log(`✓ version.ts synced to ${pkg.version}`);
} else {
  console.log(`✓ version.ts already at ${pkg.version}`);
}
